### PR TITLE
Expose "button" shadow part. Add styling demo.

### LINKED ISSUE #11: Theming Example
- Main purpose is to document using the all "parts" for theming.
- List all the parts in the API docs (vs. the old CSS mixins)
- Let's use Bootstrap as inspiration for visual end result
- Add also visual regression testing to make sure each "part" works

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/14)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-:-KhS8-dNiKoI4OeM0KB1:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-KhVinwEEUKxdCtR7jOU:-KhVinwEEUKxdCtR7jOV:b91c75s) ([raw file](https://github.com/vaadin/vaadin-button/blob/5321147412fab4acd68c30a6408757bf6faa7993/vaadin-button.html#L39)):*
> ```HTML
>       }
> 
>       [part="button"] {
> ```

I think as a good practice we should use the word container selector `~=`, so as we encourage to the reader to use it in the same way, like we do in demos

---

*[test/visual/styling.html, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-KhVjl2XrvvLwS1s6Qdc:-KhVjl2XrvvLwS1s6Qdd:biqiw47) ([raw file](https://github.com/vaadin/vaadin-button/blob/5321147412fab4acd68c30a6408757bf6faa7993/test/visual/styling.html#L16)):*
> ```HTML
>       <style>
>         [part~="button"] {
>           background: blue;
> ```

Mind to select a bg with better contrast with the black fg. When looking at the screenshots it's a bit difficult to see text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/14)*

**Comment by tomivirkki** [comment]
*[vaadin-button.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-KhVinwEEUKxdCtR7jOU:-KhW3lUEoBY2gQq3Apby:b3wsag2) ([raw file](https://github.com/vaadin/vaadin-button/blob/5321147412fab4acd68c30a6408757bf6faa7993/vaadin-button.html#L39)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think as a good practice we should use the word container selector `~=`, so as we encourage to the reader to use it in the same way, like we do in demos
</blockquote></details>

That's only for the style modules, you're not supposed to use that inside the elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/14)*

**Comment by tomivirkki** [comment]
*[vaadin-button.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-KhVinwEEUKxdCtR7jOU:-KhW4khYvoOGqaTxhDn7:byaykh5) ([raw file](https://github.com/vaadin/vaadin-button/blob/5321147412fab4acd68c30a6408757bf6faa7993/vaadin-button.html#L39)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

That's only for the style modules, you're not supposed to use that inside the elements.
</blockquote></details>

If the button gets a second part name then it would make sense, otherwise it's just confusing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/14)*

**Comment by tomivirkki** [comment]
*[test/visual/styling.html, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-KhVjl2XrvvLwS1s6Qdc:-KhW6RMDO2QXcuxBdX6T:b-1rnvom) ([raw file](https://github.com/vaadin/vaadin-button/blob/5321147412fab4acd68c30a6408757bf6faa7993/test/visual/styling.html#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Mind to select a bg with better contrast with the black fg. When looking at the screenshots it's a bit difficult to see text.
</blockquote></details>

Changed background color from blue to red

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/14)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 4 of 9 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/14#-:-KhWE16lMMKUFJeNnTAA:bnfp4nl)*

**Pull request merged**
