### PR TITLE
Remove active state when disconnected from the DOM

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to vaadin/vaadin-date-picker#505

Note: there was a similar issue with `vaadin-item` fixed previously.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/65)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-button.html, line 175 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/65#-L4BYJbwUOtVZRKJI94W:-L4BYJbwUOtVZRKJI94X:b-wvzvaa) ([raw file](https://github.com/vaadin/vaadin-button/blob/155caf4710e51da77625c7caa6cf41a48874b024/src/vaadin-button.html#L175)):*
> ```HTML
>           // reproducible in `<vaadin-date-picker>` when closing on `Cancel` or `Today` click.
>           if (this.hasAttribute('focused')) {
>             this._setFocused(false);
> ```

Just wondering, should we fix `focused` in `VaadinControlStateMixin`, same place where it was initially set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/65)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-button.html, line 175 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/65#-L4BYJbwUOtVZRKJI94W:-L4BajteYYXUyTcz5k7z:b-ujujo9) ([raw file](https://github.com/vaadin/vaadin-button/blob/155caf4710e51da77625c7caa6cf41a48874b024/src/vaadin-button.html#L175)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Just wondering, should we fix `focused` in `VaadinControlStateMixin`, same place where it was initially set?
</blockquote></details>

Was also thinking about this. Probably yes, although I do not see any possible cases other than items (already fixed) and buttons in the date-picker overlay. @tomivirkki WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/65)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-button.html, line 175 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/65#-L4BYJbwUOtVZRKJI94W:-L4Ffj3KWQ0QBZEjCqW3:bmtjo7r) ([raw file](https://github.com/vaadin/vaadin-button/blob/155caf4710e51da77625c7caa6cf41a48874b024/src/vaadin-button.html#L175)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Was also thinking about this. Probably yes, although I do not see any possible cases other than items (already fixed) and buttons in the date-picker overlay. @tomivirkki WDYT?
</blockquote></details>

Done. The focused state fix will be moved to control-state-mixin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/65)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/65#-:-L4_LumnGlIDvIN1IeUE:bnfp4nl)*

**Pull request merged**
