### PR TITLE
Bump Polymer to RC, use polymer-cli for testing

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/5)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/index.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSm890FL56UnC2NMOe:-KgSm891qSjLtXToFPw7:b-h9n2ng) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/test/index.html#L17)):*
> ```HTML
>     WCT.loadSuites([
>       'vaadin-button_test.html',
>       '../../vaadin-text-field/test/control-state.html?wc-name=vaadin-text-field'
> ```

wc-name should be vaadin-button in this case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSmCMphU6OZ_vE2mUi:-KgSmCMphU6OZ_vE2mUj:b-je8jtl) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/vaadin-button.html#L20)):*
> ```HTML
> 
> <link rel="import" href="../polymer/polymer.html">
> <link rel="import" href="../vaadin-text-field/vaadin-control-state-mixin.html">
> ```

vaadin-button

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by limonte** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSmCMphU6OZ_vE2mUi:-KgTAudGgi35ANuTQ716:b9ndnqd) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/vaadin-button.html#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

vaadin-button
</blockquote></details>

I'm not sure about this. `vaadin-control-state-mixin.html` is in the scope of `vaadin-text-field`, isn't it?

---

*[test/index.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSm890FL56UnC2NMOe:-KgTB20_sYI0tCbUR-AZ:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/test/index.html#L17)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

wc-name should be vaadin-button in this case
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by limonte** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSmCMphU6OZ_vE2mUi:-KgTE_JSMp4iUIej0RGb:bm755ix) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/vaadin-button.html#L20)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I'm not sure about this. `vaadin-control-state-mixin.html` is in the scope of `vaadin-text-field`, isn't it?
</blockquote></details>

Related PR: https://github.com/vaadin/vaadin-text-field/pull/42

---

*[test/index.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSm890FL56UnC2NMOe:-KgTBEqJAiMjrOYUjDp8:bq12w5b) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/test/index.html#L17)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

done
</blockquote></details>

after this change tests are failing, any quick su

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSmCMphU6OZ_vE2mUi:-KgTk6vZXtR-nCdbPzfG:b-spe5i) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/vaadin-button.html#L20)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Related PR: https://github.com/vaadin/vaadin-text-field/pull/42
</blockquote></details>

Sorry I misread, this is the import, so the code is ok.

---

*[test/index.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSm890FL56UnC2NMOe:-KgTl2rj10SiWqAiJCrs:b-vpafqa) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/test/index.html#L17)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

after this change tests are failing, any quick su
</blockquote></details>

Probably something wrong in the component, but this is the logic setup, we run tests against vaadin-button not against the text-field, because we run tests for that element in its repo

---

*[test/index.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgTkndaPWePu7NMk5Gu:-KgTkndaPWePu7NMk5Gv:bl90ui2) ([raw file](https://github.com/vaadin/vaadin-button/blob/febc77841e52935fab4ef0fb7299cda33e6c95d4/test/index.html#L19)):*
> ```HTML
>       '../../vaadin-text-field/test/control-state.html?wc-name=vaadin-button'
>     ].reduce(function(suites, suite) {
>       return suites.concat([suite, suite + '?dom=shadow']);
> ```

1.- you still need here the regular expression
2.- the parameter for 2.0 is wc-shadydom=true because 2.0 is already shadow by default, so dom parameter has ben removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[test/index.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSm890FL56UnC2NMOe:-KgUBZuxEWCO2rLVoZt9:bpojljc) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/test/index.html#L17)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Probably something wrong in the component, but this is the logic setup, we run tests against vaadin-button not against the text-field, because we run tests for that element in its repo
</blockquote></details>

You need to merge this, in order to make tests pass: https://github.com/vaadin/vaadin-text-field/pull/44

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by limonte** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSmCMphU6OZ_vE2mUi:-KgUJ_fAWuAJST0Qg4Px:bqlsnco) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/vaadin-button.html#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Sorry I misread, this is the import, so the code is ok.
</blockquote></details>

Please ack

---

*[test/index.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgSm890FL56UnC2NMOe:-KgUJqz-UbUouFNhtr5j:bjf7kgl) ([raw file](https://github.com/vaadin/vaadin-button/blob/6b9edc043c3aba9883d57185c4a4a0ffd50cc603/test/index.html#L17)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

You need to merge this, in order to make tests pass: https://github.com/vaadin/vaadin-text-field/pull/44
</blockquote></details>

done, thanks! Tests are passing now.

---

*[test/index.html, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-KgTkndaPWePu7NMk5Gu:-KgUJsJZlSsIYjlDiMvC:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-button/blob/febc77841e52935fab4ef0fb7299cda33e6c95d4/test/index.html#L19)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

1.- you still need here the regular expression
2.- the parameter for 2.0 is wc-shadydom=true because 2.0 is already shadow by default, so dom parameter has ben removed.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 1 of 7 files at r1.
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5#-:-KgULQDgyd4tc_XBeY4u:b-uwkowd)*

**Comment by manolo** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/5)*

**Pull request merged**
