### PR TITLE
Add active attribute

### LINKED ISSUE #4: Styling support for Active and Keyboard Focus states
Specs by @jouni

### Active

When using the mouse, the `active` state should remain for the duration of the mousedown/touchstart event, and change to the `default` state after the mouseup/touchend event. Note, that the button should not receive the `focus-ring` state at this point if it didn’t have that state before the user activated the button.

When using the keyboard, and activating the button using the Enter or Spacebar key, the `active` state should be enabled for a brief moment (500ms) and then the previous style should be restored (`default` or `focus-ring`).

### Keyboard Focused

This state should only be enabled when the user has moved the focus to the button using the keyboard Tab key.

**~Focus (browser native focus)~**

I don’t think we need to expose this state at all, at least for now. Not required.

### Implementation proposal

The states should be exposed as attributes on the host element of vaadin-button.

```html
<vaadin-button active>…</vaadin-button>
<vaadin-button focus-ring>…</vaadin-button>
```

### Other requirements

- Documentation and code examples
- Needs visual tests to verify the states are triggered correctly
- Should have basic  performance tests to catch regressions in load and startup time
- No user testing needed, as the documentation should be straightforward regarding this and there aren’t competing options for the API

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/17)

### CODE REVIEW

**Comment by jouni** [comment]
Is the active state applied also when the button is activated using the keyboard?

**Comment by Saulis** [comment]
@jouni no 🤦‍♂️

**Comment by Saulis** [comment]
So as discussed with @jouni, I dropped the 500ms delay from the keyboard activation, as it at least in the styling demo seems to give a clear visual feedback without the delay. 

However, this made me ponder does the attribute bring any additional value over `:active` ? :pondering:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-:-Ki4F5HJsLaXDv5eQUiA:boxjeqb)*

**Comment by jouni** [comment]
> However, this made me ponder does the attribute bring any additional value over :active ? :pondering:

Does that get activated also with the keyboard (both <kbd>Enter</kbd> an <kbd>Space</kbd>) in all browsers and platforms, for all elements, not just `<button>`’s? I was under the impression it doesn’t.

**Comment by jouni** [comment]
This doesn’t work in Safari at least: http://jsbin.com/yanupudida/edit?html,css,console,output

**Comment by jouni** [comment]
Did you also consider that Enter and Space work differently? Holding down Enter starts to repeat the click, while holding down Space doesn’t (it only triggers one event when you release the space key).

**Comment by platosha** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-:-KiAFUgIqCkZrO273agU:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[vaadin-button.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAGYdJymn4eEufyq2X:-KiAGYdJymn4eEufyq2Y:b-uh9bct) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/vaadin-button.html#L80)):*
> ```HTML
>           this.$.button.setAttribute('role', 'presentation');
> 
>           this._addActiveListeners();
> ```

Why to extract this only 4 lines block in a separated method, if it is not called from anywhere else.
I would avoid to have the `element._addActiveListeners` listed in the dev-tools 

---

*[test/vaadin-button_test.html, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAHBQl1RZfIbRzNPDt:-KiAHBQl1RZfIbRzNPDu:ba4tj3s) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/test/vaadin-button_test.html#L25)):*
> ```HTML
>       // MockInteractions.down/up fires only mouse events so need to use touch events when
>       // testing touch devices.
>       var IS_TOUCH_ONLY = navigator.userAgent.match(/iP(?:[oa]d|hone)|Android/);
> ```

Why all uppercased? normally they are used in static constants. I would `downcase` it,  or use `const`,  or both

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAGYdJymn4eEufyq2X:-KiAVRRUKU83vcE2QjVZ:bj61r5f) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/vaadin-button.html#L80)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why to extract this only 4 lines block in a separated method, if it is not called from anywhere else.
I would avoid to have the `element._addActiveListeners` listed in the dev-tools 
</blockquote></details>

what dev-tools?

---

*[test/vaadin-button_test.html, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAHBQl1RZfIbRzNPDt:-KiAUjNhlV_Fh0UUYz28:bllyt5a) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/test/vaadin-button_test.html#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why all uppercased? normally they are used in static constants. I would `downcase` it,  or use `const`,  or both
</blockquote></details>

just copy-pasted it directly from `gestures.html` and didn't see any reason to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAGYdJymn4eEufyq2X:-KiAVt57xVX8r-wErMHE:b-lj45xm) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/vaadin-button.html#L80)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

what dev-tools?
</blockquote></details>

chrome console

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-button_test.html, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAHBQl1RZfIbRzNPDt:-KiAW9cUiLYfwvDHDZI7:b6q8mhw) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/test/vaadin-button_test.html#L25)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

just copy-pasted it directly from `gestures.html` and didn't see any reason to change it.
</blockquote></details>

Copy-paste is not a reason for being alright. Since this is a test I dont have strong prference. not blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Comment by Saulis** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAGYdJymn4eEufyq2X:-KiDlihkERItjgdgmJ3E:b3uvuf0) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/vaadin-button.html#L80)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

chrome console
</blockquote></details>

I extracted the functionality not because it would be reused, but to make the `ready()` function shorter. It could be improved even further by extracting the assignment of roles functionality.

I fail to see what's wrong in having small, dedicated private functions and don't understand why it is a problem in developer tools since the element already inherits hundreds of properties and functions from `HTMLElement` and `Polymer.Element`.

---

*[test/vaadin-button_test.html, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAHBQl1RZfIbRzNPDt:-KiDk_DDaZMQgGWNUFLc:b-ccnxsw) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/test/vaadin-button_test.html#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Copy-paste is not a reason for being alright. Since this is a test I dont have strong prference. not blocker
</blockquote></details>

I think we can remove the whole check, assume that gesture events mixin is being imported and fire directly events `down` and `up` for simplicity. 

Ideally, we could've just used `MockInteractions.down(node)` and `MockInteractions.up(node)`,  but unfortunately, that doesn't work on currently properly on touch devices in Polymer 2.0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/17#-KiAGYdJymn4eEufyq2X:-KiELb7uVk_3yHQOHVNw:b-u82d3c) ([raw file](https://github.com/vaadin/vaadin-button/blob/76c6c467b3bb51a9b42b2db5423de0be937f33ed/vaadin-button.html#L80)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I extracted the functionality not because it would be reused, but to make the `ready()` function shorter. It could be improved even further by extracting the assignment of roles functionality.

I fail to see what's wrong in having small, dedicated private functions and don't understand why it is a problem in developer tools since the element already inherits hundreds of properties and functions from `HTMLElement` and `Polymer.Element`.
</blockquote></details>

What I meant, is

- ready, is only 3 LOC (short function), adding 4 lines more is only 7 LOC (also short)
- by adding an additional method, we need at least 3 LOC.

So, I studied as a good practice extract a method when you either, need to share a block, or when the complexity of the original method is clarified by the extraction, but few line methods are not justified and can add complexity.

Anyways, I don't thing we go anyway with this discussion, we come from different schools. I only suggested that it's not necessary the extraction. So leave this as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/17)*

**Pull request merged**
