### PR TITLE
Move IE11 to cron build

### PR DESCRIPTION
**Pull request by limonte**
To test locally  run:

```sh
polymer test --env=saucelabs-cron
```

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/40)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsNjMPuFTL6BzYKfxo3:bnfp4nl)*

**Comment by tomivirkki** [comment]
Why wouldn’t we want to test IE11 for every PR? We still need to support IE11

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsNkfqjPytB0L8a_-Ws:b-pbjc0r)*

**Comment by manolo** [comment]
I do prefer to have it for all PR

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsNpCV0r6jUcHF7lNHP:b-6jpb4t)*

**Comment by limonte** [comment]
> Why wouldn’t we want to test IE11 for every PR? We still need to support IE11

This solution is also temporary, it will trigger IE11 tests once a day instead of not testing in IE11 at all.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsNqu2ndS-w-N4wbK0s:b-k2kbtp)*

**Comment by limonte** [comment]
> I do prefer to have it for all PR

Could you please rephrase this sentence? I'm not sure I understand it.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsNrCeqvDc6DQGG6MJP:besaz7i)*

**Comment by tomivirkki** [comment]
> This solution is also temporary, it will trigger IE11 tests once a day instead of not testing in IE11 at all.

If it’s temporary then the comment should be moved also. But enabling the tests to be run nightly indicates that the tests are passing again (?) If that’s the case, we should just re-enable IE11 tests as part of saucelabsPlatforms. Moving them to cron tests will result in false positive PR’s and red cron builds.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsNsWxyy889OJotA9k_:bfxospc)*

**Comment by limonte** [comment]
> But enabling the tests to be run nightly indicates that the tests are passing again (?) If that’s the case, we should just re-enable IE11 tests as part of saucelabsPlatforms.

I have no idea wtf is wrong with SauceLabs. Maybe running IE11 ans iOS platforms at the same time causes the timeout issue. Let's try this solution and see if it will work fine. If not, I will revert the change.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/40#-:-KsO3F3pG8HEQ6j_DgWb:b-rt87vr)*

**Pull request closed without merging**
