### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by jouni**
- Updated look’n’feel

- The button now aligns naturally on the baseline in all browsers without any hacks. The core alignment styles are part of the unthemed source element.

- Removed the wrapping native button (and the “button” styling part), to reduce necessary CSS hacks for IE11. The native button is still kept in the DOM, on top of the whole button, to reduce the risk of regressions.

- Added three new styling parts, named “label” (which is the default slot), “prefix” and “suffix”. The prefix and suffix parts are named slots.

- Split the Valo theme module into multiple style modules which are then gathered in the main theme module. This is mostly future-proofing at this point, but it allows us to provide more flexibility in customization in the future.

- Added a test page for the Valo theme and its variations (for manual testing at this point, but could/should be automated eventually)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/57)

### CODE REVIEW

**Comment by web-padawan** [comment]
We have already discussed the Valo screenshot with @tomivirkki and decided not to use theme variations in the README screenshot, because these are theme-specific. Should we change our decision now?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/vaadin-button.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0Jg-cuhlVWZftFhdYc:-L0Jg-cuhlVWZftFhdYd:b-ohtekx) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/src/vaadin-button.html#L71)):*
> ```HTML
> 
>       #button {
>         position: absolute;
> ```

this will break if user changes position on host element to `static` for some reason.

---

*[src/vaadin-button.html, line 76 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0JiostZ9136esGMYZW:-L0JiostZ9136esGMYZX:bf7iu4o) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/src/vaadin-button.html#L76)):*
> ```HTML
>         width: 100%;
>         height: 100%;
>         opacity: 0;
> ```

this makes impossible to use the unthemed element , at least it no longer looks like a plain HTML button

---

*[test/visual/valo.html, line 3 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0JndxG59rkVJ5M8s0o:-L0JndxG59rkVJ5M8s0p:b-9vrl2z) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/test/visual/valo.html#L3)):*
> ```HTML
> <!doctype html>
> <script src="../../../webcomponentsjs/webcomponents-loader.js"></script>
> <link rel="import" href="../../../vaadin-button/vaadin-button.html">
> ```

nit: import path can be reduced since this test file is now in the `vaadin-button` repo

---

*[theme/valo/vaadin-button.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0JmetFZO4zG68yqVSX:-L0JmetFZO4zG68yqVSY:b-aodqr) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/theme/valo/vaadin-button.html#L67)):*
> ```HTML
>       /* Disabled */
> 
>       :host([disabled][disabled]) {
> ```

nit: duplicate attribute

---

*[theme/valo/vaadin-button.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0Jmynn2t2ltNfWUIcj:-L0Jmynn2t2ltNfWUIck:ber5j7l) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/theme/valo/vaadin-button.html#L79)):*
> ```HTML
>     <style>
>       :host {
>         position: relative;
> ```

nit: the `vaadin-button` element already has this state, it it added here intentionally?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-:-L0Jlrkj6iBrLXJ_nC_j:bn9pt7y)*

**Comment by jouni** [comment]
Right, that’s a good point. Not 100% sure. Since Valo is the default, it felt appropriate, and gives a bit more incentive to try out our button. Though, I advocated against pointing out the theme variations in the recent skeleton readme update.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/vaadin-button.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0Jg-cuhlVWZftFhdYc:-L0K63boDkOpMEbKr3c0:bkc18kl) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/src/vaadin-button.html#L71)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

this will break if user changes position on host element to `static` for some reason.
</blockquote></details>

That’s true. Should probably add `!important` on the host position.

---

*[src/vaadin-button.html, line 76 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0JiostZ9136esGMYZW:-L0K6945THPBub-nRQrb:b-wswo3r) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/src/vaadin-button.html#L76)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

this makes impossible to use the unthemed element , at least it no longer looks like a plain HTML button
</blockquote></details>

Yes. I think there was some sort of consensus that the users should never use an unthemed version.

Also, having our elements look like native elements is something I’m moving away from. I think one big reason users opt to use non-native elements is that they look different than native elements.

---

*[theme/valo/vaadin-button.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0JmetFZO4zG68yqVSX:-L0K7MzOgl9BIw1PnIzS:b-5ryekj) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/theme/valo/vaadin-button.html#L67)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: duplicate attribute
</blockquote></details>

This was actually on purpose so that always wins some of the more specific selectors, like the primary and color variation styles.

---

*[theme/valo/vaadin-button.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0Jmynn2t2ltNfWUIcj:-L0K7X7bycJnWUL41Qxn:bee3mdg) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/theme/valo/vaadin-button.html#L79)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: the `vaadin-button` element already has this state, it it added here intentionally?
</blockquote></details>

Accidentally remaining from the old theme. But I also thought it would be good to have it explicitly here, since the ::before and ::after elements expect it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-:-L0K5j2G2BpOLVtuROp8:b-gn9ijd)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/vaadin-button.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0Jg-cuhlVWZftFhdYc:-L0KOQvossz2xaXus5ow:b-xyg3m6) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/src/vaadin-button.html#L71)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

That’s true. Should probably add `!important` on the host position.
</blockquote></details>

we actually could move `button` element up in the DOM and remove `top` and `left` coordinates, that way it would become taken out from the document flow but not positioned, so the `position: relative` on the host element would be not necessary. But this would break when setting `padding` on the host element. 

Anyways, `!important` approach doesn't seem good to me but is not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57)*

**Comment by jouni** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/vaadin-button.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0Jg-cuhlVWZftFhdYc:-L0LWhZn0AWoiI9Vvgnk:b-w6nprh) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/src/vaadin-button.html#L71)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

we actually could move `button` element up in the DOM and remove `top` and `left` coordinates, that way it would become taken out from the document flow but not positioned, so the `position: relative` on the host element would be not necessary. But this would break when setting `padding` on the host element. 

Anyways, `!important` approach doesn't seem good to me but is not a blocker.
</blockquote></details>

That’s actually a nice idea, but like you said, it breaks with the host padding.

I also tried hiding the native button completely with `display: none`, but that causes the page to scroll when activating the button with the space key. So apparently the native button needs to be in the DOM.

I now resorted to `!important` – if a developer wants to override that, they at least know they are possibly causing issues.

---

*[test/visual/valo.html, line 3 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-L0JndxG59rkVJ5M8s0o:-L0Li2Q6SsoMwAdsvpJq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/b66873690d7b95a4bc7ae946d249ee392ada07e4/test/visual/valo.html#L3)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: import path can be reduced since this test file is now in the `vaadin-button` repo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-:-L0OKTDL3Oqr2bWucm-z:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-:-L0OSZl6Q1xvE8k0KLOH:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57#-:-L0Ox3Zk_PSHCxKtJAru:bg7igkv)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/57)*

**Pull request merged**
