### PR TITLE
Replace iron-component-page with api-doc-viewer

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/239
Depends on https://github.com/vaadin/vaadin-text-field/pull/61 being merged first.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/13)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-KhWkDUkc4tbwUqbdDyu:-KhWkDUkc4tbwUqbdDyv:bnoexr7) ([raw file](https://github.com/vaadin/vaadin-button/blob/e5aeca88e03d1cd90b9975cfe2d350ccc29e3fc9/vaadin-button.html#L37)):*
> ```HTML
>       /**
>       * `<vaadin-button>` is a Polymer element for customized buttons.
>       *
> ```

nit: add a space left to all lines but the first one in the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/13)*

**Comment by tomivirkki** [comment]
*[docs.json, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-KhXE1P1XRayyaOnLmmL:-KhXE1P1XRayyaOnLmmM:bfu7l6n) ([raw file](https://github.com/vaadin/vaadin-button/blob/e5aeca88e03d1cd90b9975cfe2d350ccc29e3fc9/docs.json#L1)):*
> ```JSON
> {
> ```

Should this be updated for this PR? Or is this only run on deployment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/13)*

**Comment by tomivirkki** [comment]
*[docs.json, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-KhXE1P1XRayyaOnLmmL:-KhXFJ8_qbfWvn3Pjule:bsdk64m) ([raw file](https://github.com/vaadin/vaadin-button/blob/e5aeca88e03d1cd90b9975cfe2d350ccc29e3fc9/docs.json#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should this be updated for this PR? Or is this only run on deployment?
</blockquote></details>

*run -> updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/13)*

**Comment by Saulis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs.json, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-KhXE1P1XRayyaOnLmmL:-KhXmUQJHnr1HmoYeMko:bu745vm) ([raw file](https://github.com/vaadin/vaadin-button/blob/e5aeca88e03d1cd90b9975cfe2d350ccc29e3fc9/docs.json#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

*run -> updated
</blockquote></details>

Should be updated when API changes, updated now.

---

*[vaadin-button.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-KhWkDUkc4tbwUqbdDyu:-KhXmZ1ghLUkkLVGj9EQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/e5aeca88e03d1cd90b9975cfe2d350ccc29e3fc9/vaadin-button.html#L37)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: add a space left to all lines but the first one in the comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/13)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-:-KhXzkIr6RZlmAK0vH2x:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/13#-:-KhaW1_tiMJ2Uofx8n52:bnfp4nl)*

**Pull request merged**
