### PR TITLE
Adding Aria attributes

### LINKED ISSUE #6: Accessibility support
User should be able to define a label which gets announced by a screen reader when the button gets focused.

Also, correct aria roles and states should be set, see: https://www.w3.org/TR/wai-aria-practices-1.1/#button

- reader should announce contents by default, and `aria-label` can be used to override the announcement

### PR DESCRIPTION
**Pull request by manolo**
Fixes #6

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/9)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-button.html, line 48 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgtEGHcotEtfavQ3p1N:-KgtEGHcotEtfavQ3p1O:bd2ro6d) ([raw file](https://github.com/vaadin/vaadin-button/blob/9dd7f0b6cb88d088125c46bbe3c3039a8b82e8df/vaadin-button.html#L48)):*
> ```HTML
>         return {
>           /**
>            * Defines a string value that labels the current element for accesibility.
> ```

"accesibility" -> "accessibility"

---

*[demo/index.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgtEN0rd6NXnSFeky41:-KgtEN0rd6NXnSFeky42:b-h60q4p) ([raw file](https://github.com/vaadin/vaadin-button/blob/9dd7f0b6cb88d088125c46bbe3c3039a8b82e8df/demo/index.html#L35)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Button with Accesible Label</h3>
> ```

"Accesible" -> "Accessible"

---

*[demo/index.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgtEQ89ek0cXOWBrOnG:-KgtEQ89ek0cXOWBrOnH:b-h60q4p) ([raw file](https://github.com/vaadin/vaadin-button/blob/9dd7f0b6cb88d088125c46bbe3c3039a8b82e8df/demo/index.html#L38)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <vaadin-button aria-label="Click Me">Accesible</vaadin-button>
> ```

"Accesible" -> "Accessible"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-button.html, line 48 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgtEGHcotEtfavQ3p1N:-KgtGHvJlytRfoSLESTx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/9dd7f0b6cb88d088125c46bbe3c3039a8b82e8df/vaadin-button.html#L48)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"accesibility" -> "accessibility"
</blockquote></details>

Done.

---

*[demo/index.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgtEN0rd6NXnSFeky41:-KgtGJ-OM8Vgj-aGQ_zX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/9dd7f0b6cb88d088125c46bbe3c3039a8b82e8df/demo/index.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"Accesible" -> "Accessible"
</blockquote></details>

Done.

---

*[demo/index.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgtEQ89ek0cXOWBrOnG:-KgtGJ_e6AJCKDNY9ZO9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/9dd7f0b6cb88d088125c46bbe3c3039a8b82e8df/demo/index.html#L38)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"Accesible" -> "Accessible"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgtGoL0l5XYtFQ91as8:bnfp4nl)*

**Comment by platosha** [comment]
Incomplete, aria roles are incorrect. From the VoiceOver’s point of view, `<vaadin-button>` is a group with a button inside.

When navigating with voiceover cursor, it says “Click me, group”.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgtPdb84gyEUUlCdto9:b-52ddgl)*

**Comment by platosha** [comment]
Instead, I would:
- set `presentation` role to the `<button>`
- set `button` role on the host
- remove `aria-label` property and binding, it will work natively on the host then.

No host group, no need to bind aria-label.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgtQtSgdvBiHQeNdYRH:b-sy0w0d)*

**Comment by manolo** [comment]
How do you get that message, or how do I have to navigate to hear it?
I use tab or shift tab, and when the button is focused it correctly said "Click me, button"

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgtV9nG2vFLSzX0YUtN:b-50tvc2)*

**Comment by platosha** [comment]
@manolo try VoiceOver cursor keys: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+(<kbd>←</kbd>|<kbd>→</kbd>)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgxEP-Bu_2x4qb1ZaQ-:b-8k8fjl)*

**Comment by tomivirkki** [comment]
One difference I noticed now that @anton mentioned it, while tabbing normally, after declaring the label:
`<vaadin-button>`: “You are currently on a button, inside of a group.”
`<button>`: “You are currently on a button, inside of web content.”
Don’t know if this is related.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgxJ8VDr_8mA8wSpu8W:bmo95xk)*

**Comment by Saulis** [comment]
:+1: to what @platosha suggested, works perfectly like that and we should use the same approach later with `vaadin-text-field`

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-Kgxd46rlriMJLXMjJsp:b-3j7ub5)*

**Comment by manolo** [comment]
Applied the @platosha approach. It works also in Chromevox.
The inside a group or a web content, seems to be more sense with this approach, since now the button is announced in a web content which is actually the place of the web component.

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-:-KgxiJthK32uWpjdZePS:b-u9n3h)*

**Comment by Saulis** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 48 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmU-ImRK2av_7UvhJ:-KgxmU-ImRK2av_7UvhK:b-my7h50) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L48)):*
> ```HTML
>            * Defines a string value that labels the current element for accessibility.
>            */
>           ariaLabel: {
> ```

This property isn't needed since native attribute can be used without any modifications

---

*[vaadin-button.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmWpRIWiB2V-JDp7j:-KgxmWpRIWiB2V-JDp7k:bezcn1z) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L62)):*
> ```HTML
>         // since the focus is moved programatically, and the second on a group.
>         this.setAttribute('role', 'button');
>         this.$.button.setAttribute('role', 'presentation');
> ```

Rather add the attribute directly on the `<button>` in the template

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 48 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmU-ImRK2av_7UvhJ:-Kgy05xUJzBaf9o--IRx:b-ys7dlc) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L48)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This property isn't needed since native attribute can be used without any modifications
</blockquote></details>

This is intentional, otherwise the imperative`$0.ariaLabel = 'FOO'` does not work

---

*[vaadin-button.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmWpRIWiB2V-JDp7j:-Kgy0FCVhwTb3yDmoSY8:b8xgwnv) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L62)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Rather add the attribute directly on the `<button>` in the template
</blockquote></details>

Since I cannot set declaratively the host attribute, I do prefer to have both in the same place, because it's more readable, and easy to understand for the reader in a quick view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by Saulis** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-button.html, line 48 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmU-ImRK2av_7UvhJ:-Kgy0jzHHD3-8FpYWzl0:b2elfqv) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L48)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This is intentional, otherwise the imperative`$0.ariaLabel = 'FOO'` does not work
</blockquote></details>

I wouldn't expect that to work since it doesn't work on any native elements either. The expected way to use it imperatively is `$0.setAttribute('aria-label', 'foo');` 
Also, adding a custom property would imply that we should also add properties other aria related attributes like `ariaDisabled` and more. There's no added value in overriding native attributes.

---

*[vaadin-button.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmWpRIWiB2V-JDp7j:-Kgy24qMwcqUeWfY0Ukt:b32w1t) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L62)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Since I cannot set declaratively the host attribute, I do prefer to have both in the same place, because it's more readable, and easy to understand for the reader in a quick view.
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 48 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmU-ImRK2av_7UvhJ:-Kgy3ThHEiiKr__Ys0Pk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L48)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I wouldn't expect that to work since it doesn't work on any native elements either. The expected way to use it imperatively is `$0.setAttribute('aria-label', 'foo');` 
Also, adding a custom property would imply that we should also add properties other aria related attributes like `ariaDisabled` and more. There's no added value in overriding native attributes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by tomivirkki** [comment]
*[vaadin-button.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmWpRIWiB2V-JDp7j:-Kgy3EPdHLqtcGbP9bSP:b-wepalm) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L62)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

I don't see that it justifies to use imperative syntax here. If that was the case, we should set all our internal attributes imperatively in every P2 element just because we can't set the host attribute declaratively.

The upgrade guide also suggests to replace `hostAttributes` with `_ensureAttribute()` https://www.polymer-project.org/2.0/docs/upgrade#upgrading-to-class-based-elements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmWpRIWiB2V-JDp7j:-Kgy3RifMLGD0GUGtar-:b-ngnl70) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L62)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I don't see that it justifies to use imperative syntax here. If that was the case, we should set all our internal attributes imperatively in every P2 element just because we can't set the host attribute declaratively.

The upgrade guide also suggests to replace `hostAttributes` with `_ensureAttribute()` https://www.polymer-project.org/2.0/docs/upgrade#upgrading-to-class-based-elements
</blockquote></details>

_ensureAttibute is not a good idea here, we don't want that the user changes the role of this element.

Still not convinced about using declarative. I'm not defending to set all our attrs imperativelly, I only say that in THIS case, where we are using an specific approach for making accessibility work and not the logical way of just delegating on the native button, it is easier to explain to the reader why and how we deal with the issue. But if this is going to be a blocker, I can change the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by tomivirkki** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-button.html, line 62 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-KgxmWpRIWiB2V-JDp7j:-KgyEfilfqrjHxDbJUMh:b2ngvnt) ([raw file](https://github.com/vaadin/vaadin-button/blob/5163cf87779d91277d6fa39c14c90c0326be7d6d/vaadin-button.html#L62)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

_ensureAttibute is not a good idea here, we don't want that the user changes the role of this element.

Still not convinced about using declarative. I'm not defending to set all our attrs imperativelly, I only say that in THIS case, where we are using an specific approach for making accessibility work and not the logical way of just delegating on the native button, it is easier to explain to the reader why and how we deal with the issue. But if this is going to be a blocker, I can change the code.
</blockquote></details>

...

---

*[vaadin-button.html, line 46 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-Kgy5U6sC4yFG41UGdp3:-Kgy5U6sC4yFG41UGdp4:bvh3gek) ([raw file](https://github.com/vaadin/vaadin-button/blob/1edbb61557a98051f5450845e4c62744a62866e3/vaadin-button.html#L46)):*
> ```HTML
>         super.ready();
> 
>         // Leaving default role in the native button, makes navigation anoucement
> ```

announcement

---

*[vaadin-button.html, line 48 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-Kgy5cBjucV0IERk1crc:-Kgy5cBjucV0IERk1crd:b7lib45) ([raw file](https://github.com/vaadin/vaadin-button/blob/1edbb61557a98051f5450845e4c62744a62866e3/vaadin-button.html#L48)):*
> ```HTML
>         // Leaving default role in the native button, makes navigation anoucement
>         // being different when using focus navigation (tab) versus using normal
>         // navigation (arrows). The first way anounces the label on a button
> ```

announces

---

*[vaadin-button.html, line 49 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-Kgy5S9S6KEM_5Gs7z2s:-Kgy5S9TGQ4uD9Ii9YN6:baf4nzn) ([raw file](https://github.com/vaadin/vaadin-button/blob/1edbb61557a98051f5450845e4c62744a62866e3/vaadin-button.html#L49)):*
> ```HTML
>         // being different when using focus navigation (tab) versus using normal
>         // navigation (arrows). The first way anounces the label on a button
>         // since the focus is moved programatically, and the second on a group.
> ```

programmatically

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-button.html, line 46 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-Kgy5U6sC4yFG41UGdp3:-KgyFjJem_cyIXy4YwDl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/1edbb61557a98051f5450845e4c62744a62866e3/vaadin-button.html#L46)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

announcement
</blockquote></details>

Done.

---

*[vaadin-button.html, line 48 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-Kgy5cBjucV0IERk1crc:-KgyFiDJCHDoAaJU95_H:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/1edbb61557a98051f5450845e4c62744a62866e3/vaadin-button.html#L48)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

announces
</blockquote></details>

Done.

---

*[vaadin-button.html, line 49 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-button/9#-Kgy5S9S6KEM_5Gs7z2s:-KgyFi238_tisscxb6uq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/1edbb61557a98051f5450845e4c62744a62866e3/vaadin-button.html#L49)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

programmatically
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Comment by manolo** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/9)*

**Pull request merged**
