### PR TITLE
Prepare for P3

### LINKED ISSUE #74: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by platosha**
Fixes #74

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/78)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 10 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 43 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-button/78#-L8biEjyE1jMjBEYEaD5:-L8biEjyE1jMjBEYEaD6:bnt6ia2) ([raw file](https://github.com/vaadin/vaadin-button/blob/2b333319317b0962bb7836112d2231419e5c0a8b/package.json#L43)):*
> ```JSON
>     "stylelint-config-vaadin": "latest",
>     "web-component-tester": "^6.1.5",
>     "yargs": "^8.0.0"
> ```

BTW let's also remove polymer-cli from dependencies.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button/78)*

**Comment by platosha** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/78#-L8biEjyE1jMjBEYEaD5:-L8bieBW8CsubC7yYC37:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button/blob/2b333319317b0962bb7836112d2231419e5c0a8b/package.json#L43)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW let's also remove polymer-cli from dependencies.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/78)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button/78#-:-L8bj0UJ-gkfs_4BlZMn:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:
But let's decide on theming approach naming before merging

---

Reviewed 9 of 11 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button/78#-:-L8fQyWK4hiqYQXD7LyA:b-rc9120)*

**Pull request merged**
