### PR TITLE
Remove control-state-mixin visual tests 

### PR DESCRIPTION
**Pull request by limonte**
`control-state-mixin`'s functionality should be tested in `control-state-mixin`, not here.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/51)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Isn't this case for testing how the button appears visually when it has a focus-ring?

**Comment by limonte** [comment]
Yes, it is. But visual appearance is **the theme responsibility**. Stable theme release should have visual tests with all elements including the button.

**Comment by tomivirkki** [comment]
Ah, yes, the default theme doesn't have anything for the focus-ring. LGTM

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/51#-:-KucduLUc6VwKLTQ1xXo:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/51#-:-KuceU-1IAfcq1DuoXxX:bnfp4nl)*

**Pull request merged**
