### PR TITLE
Align focus-ring style with other components

### PR DESCRIPTION
**Pull request by limonte**
Connected to #32 

Also, move styles to the default theme.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button/43)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/43#-Ksd6aP4THGD318jOdjf:-Ksd6aP4THGD318jOdjg:b-qv45yz) ([raw file](https://github.com/vaadin/vaadin-button/blob/595160b08d571ce453cd0638c3ab32b5b84f519c/vaadin-button.html#L20)):*
> ```HTML
> </dom-module>
> 
> <dom-module id="vaadin-button">
> ```

Why move all the styles to default theme? That's a breaking change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/43)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/43#-Ksd6aP4THGD318jOdjf:-Ksd80MTo_MWV82vyFhy:bfs5u56) ([raw file](https://github.com/vaadin/vaadin-button/blob/595160b08d571ce453cd0638c3ab32b5b84f519c/vaadin-button.html#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why move all the styles to default theme? That's a breaking change
</blockquote></details>

To be aligned with other components:

- https://github.com/vaadin/vaadin-radio-button/blob/master/vaadin-radio-button.html#L12-L40
- https://github.com/vaadin/vaadin-checkbox/blob/master/vaadin-checkbox.html#L12-L41

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/43)*

**Comment by tomivirkki** [comment]
*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/43#-Ksd6aP4THGD318jOdjf:-Ksh7VeGLbPmA6xDC0Rk:bcxcnae) ([raw file](https://github.com/vaadin/vaadin-button/blob/595160b08d571ce453cd0638c3ab32b5b84f519c/vaadin-button.html#L20)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

To be aligned with other components:

- https://github.com/vaadin/vaadin-radio-button/blob/master/vaadin-radio-button.html#L12-L40
- https://github.com/vaadin/vaadin-checkbox/blob/master/vaadin-checkbox.html#L12-L41
</blockquote></details>

How about https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L61 then? There is a clear separation between functional and non-functional styles there. Why do you think these `<vaadin-button>` styles are non-functional?

For example if the internal `<button>` didn’t take 100% space of the host element and you set the `<vaadin-button>` to have `100px` width, the internal button will still have default width instead of `100px`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/43)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-button.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button/43#-Ksd6aP4THGD318jOdjf:-KshFGbh5ijGTAtsUKeX:b-v1f876) ([raw file](https://github.com/vaadin/vaadin-button/blob/595160b08d571ce453cd0638c3ab32b5b84f519c/vaadin-button.html#L20)):*
> Why do you think these <vaadin-button> styles are non-functional?

It's unclear for me which style are functional and which aren't. If there's any explanation somewhere I would like to read it.

Reverted to the initial state with styling for `focus-ring`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button/43)*

**Comment by limonte** [comment]
Looks like this isn't the proper way to fix the issue. Closing.

**Pull request closed without merging**
